language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install coveralls
  - pip install flake8
script:
  - flake8 .
  - coverage run -m unittest discover -s tests -p *_tests.py
after_success:
    coveralls
sudo: false